### ISSUE TITLE
hi sir how can I contact you

### ISSUE THREAD

**Issue by bouhamla7** [WBRK-dev/wanime#1]
hi sir how can I contact you

**Comment by WBRK-dev** [comment]
Hello,

Please describe why you would want to contact me.
I do not want to give my email address to someone without knowing their reason for wanting to contact me.

Kind regard

**Comment by bouhamla7** [comment]
just i need .sql file to install your wow website in my cpanel

**Comment by WBRK-dev** [comment]
Closing this issue, feel free to open it again if something comes up.
